I'm sorry, but an uncaught exception occurred.

While loading <'Image' u'./images/personajes/vilma/VilmaRopa.png'>:
  File "game/script.rpy", line 3, in script
    with dissolve
IOError: Couldn't find file './images/personajes/vilma/VilmaRopa.png'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 3, in script
    with dissolve
  File "renpy/ast.py", line 1443, in execute
    renpy.exports.with_statement(trans, paired)
  File "renpy/exports.py", line 1684, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2762, in do_with
    clear=clear)
  File "renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3839, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "renpy/display/core.py", line 2565, in draw_screen
    renpy.config.screen_height,
  File "render.pyx", line 492, in renpy.display.render.render_screen
  File "render.pyx", line 263, in renpy.display.render.render
  File "renpy/display/layout.py", line 826, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "renpy/display/transition.py", line 368, in render
    top = render(self.new_widget, width, height, st, at)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "renpy/display/layout.py", line 826, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "renpy/display/layout.py", line 826, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "renpy/display/transform.py", line 733, in render
    return transform_render(self, width, height, st, at)
  File "accelerator.pyx", line 187, in renpy.display.accelerator.transform_render
  File "render.pyx", line 263, in renpy.display.render.render
  File "renpy/display/image.py", line 501, in render
    return wrap_render(self.target, width, height, st, at)
  File "renpy/display/image.py", line 307, in wrap_render
    rend = render(child, w, h, st, at)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "renpy/display/im.py", line 625, in render
    return cache.get(self, render=True)
  File "renpy/display/im.py", line 287, in get
    surf = image.load()
  File "renpy/display/im.py", line 706, in load
    raise e
IOError: Couldn't find file './images/personajes/vilma/VilmaRopa.png'.

Windows-10-10.0.18362
Ren'Py 7.4.11.2266
prueba_1 1.0
Sun May 29 16:17:50 2022
